default:
    path: '/'
    defaults: { _controller: AppBundle:Default:index }

articles:
    type: rest
    resource: AppBundle\Controller\ArticleController

authors:
    type: rest
    resource: AppBundle\Controller\AuthorController